
import br.com.lanchonete.pessoas.Cliente;
import br.com.lanchonete.pessoas.Colaborador;
import br.com.lanchonete.produtos.Pedido;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Classe representativa da interface de opções dos Colaboradores do sistema 
 * @author Iago Mateus Ávila Fernandes
 * @author Mateus Henrique Machado
 */
public class TelaPrincipalColab extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalColab
     */
    public TelaPrincipalColab() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        consPedido = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cpfCliente = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPedidos = new javax.swing.JTable();
        extPedido = new javax.swing.JPanel();
        gerarExtratos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        extratosPedidosTabela = new javax.swing.JTable();
        relCliente = new javax.swing.JPanel();
        totalClientes = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        relClienteTable = new javax.swing.JTable();
        gerarRelCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        relColab = new javax.swing.JPanel();
        gerarRelColab = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        relColabTable = new javax.swing.JTable();
        relProdutos = new javax.swing.JPanel();
        gerarRelProduto = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        relProdutoTable = new javax.swing.JTable();
        relVendas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        diaMintxt = new javax.swing.JTextField();
        mesMintxt = new javax.swing.JTextField();
        diaMaxtxt = new javax.swing.JTextField();
        anoMintxt = new javax.swing.JTextField();
        anoMaxtxt = new javax.swing.JTextField();
        mesMaxtxt = new javax.swing.JTextField();
        gerarRelVendas = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        relVendasTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pedidosEntregues = new javax.swing.JLabel();
        receitaTotal = new javax.swing.JLabel();
        pedidosAceitos = new javax.swing.JLabel();
        pedidosCancelados = new javax.swing.JLabel();
        sobre = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Best Lanches - Colaborador");
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);
        setResizable(false);

        jPanel4.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel1, "card8");

        consPedido.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cpfCliente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfClienteActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Listar pedidos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("CPF do Cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        listPedidos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        listPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pedido", "Data", "Hora", "Valor (R$)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listPedidos.setGridColor(new java.awt.Color(204, 204, 204));
        listPedidos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(listPedidos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout consPedidoLayout = new javax.swing.GroupLayout(consPedido);
        consPedido.setLayout(consPedidoLayout);
        consPedidoLayout.setHorizontalGroup(
            consPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consPedidoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(consPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        consPedidoLayout.setVerticalGroup(
            consPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consPedidoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(consPedido, "consPedido");

        extPedido.setBackground(new java.awt.Color(255, 255, 255));

        gerarExtratos.setBackground(new java.awt.Color(255, 153, 0));
        gerarExtratos.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        gerarExtratos.setForeground(new java.awt.Color(255, 255, 255));
        gerarExtratos.setText("Gerar Extratos");
        gerarExtratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarExtratosActionPerformed(evt);
            }
        });

        extratosPedidosTabela.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        extratosPedidosTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Id_Pedido", "Valor Total", "Data", "Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        extratosPedidosTabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(extratosPedidosTabela);

        javax.swing.GroupLayout extPedidoLayout = new javax.swing.GroupLayout(extPedido);
        extPedido.setLayout(extPedidoLayout);
        extPedidoLayout.setHorizontalGroup(
            extPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extPedidoLayout.createSequentialGroup()
                .addGroup(extPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(extPedidoLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(gerarExtratos, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(extPedidoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        extPedidoLayout.setVerticalGroup(
            extPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extPedidoLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(gerarExtratos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jPanel4.add(extPedido, "extPedido");

        relCliente.setBackground(new java.awt.Color(255, 255, 255));

        totalClientes.setBackground(new java.awt.Color(255, 255, 255));
        totalClientes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        totalClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalClientes.setToolTipText("");
        totalClientes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 2, true));
        totalClientes.setPreferredSize(new java.awt.Dimension(50, 24));

        relClienteTable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        relClienteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Telefone", "Endereço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        relClienteTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(relClienteTable);
        if (relClienteTable.getColumnModel().getColumnCount() > 0) {
            relClienteTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            relClienteTable.getColumnModel().getColumn(1).setPreferredWidth(180);
            relClienteTable.getColumnModel().getColumn(2).setPreferredWidth(40);
            relClienteTable.getColumnModel().getColumn(3).setHeaderValue("Endereço");
        }

        gerarRelCliente.setBackground(new java.awt.Color(255, 153, 0));
        gerarRelCliente.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        gerarRelCliente.setForeground(new java.awt.Color(255, 255, 255));
        gerarRelCliente.setText("Gerar Relatório");
        gerarRelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarRelClienteActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Total de Clientes Cadastrados");

        javax.swing.GroupLayout relClienteLayout = new javax.swing.GroupLayout(relCliente);
        relCliente.setLayout(relClienteLayout);
        relClienteLayout.setHorizontalGroup(
            relClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relClienteLayout.createSequentialGroup()
                .addGroup(relClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(relClienteLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(gerarRelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(relClienteLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, relClienteLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(relClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, relClienteLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, relClienteLayout.createSequentialGroup()
                        .addComponent(totalClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(356, 356, 356))))
        );
        relClienteLayout.setVerticalGroup(
            relClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relClienteLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(gerarRelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jPanel4.add(relCliente, "relCliente");

        relColab.setBackground(new java.awt.Color(255, 255, 255));

        gerarRelColab.setBackground(new java.awt.Color(255, 153, 0));
        gerarRelColab.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        gerarRelColab.setForeground(new java.awt.Color(255, 255, 255));
        gerarRelColab.setText("Gerar Relatório");
        gerarRelColab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarRelColabActionPerformed(evt);
            }
        });

        relColabTable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        relColabTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CPF", "Nome", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        relColabTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(relColabTable);
        if (relColabTable.getColumnModel().getColumnCount() > 0) {
            relColabTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            relColabTable.getColumnModel().getColumn(1).setPreferredWidth(180);
            relColabTable.getColumnModel().getColumn(2).setPreferredWidth(40);
        }

        javax.swing.GroupLayout relColabLayout = new javax.swing.GroupLayout(relColab);
        relColab.setLayout(relColabLayout);
        relColabLayout.setHorizontalGroup(
            relColabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relColabLayout.createSequentialGroup()
                .addGroup(relColabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(relColabLayout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(gerarRelColab, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(relColabLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        relColabLayout.setVerticalGroup(
            relColabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relColabLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(gerarRelColab, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jPanel4.add(relColab, "relColab");

        relProdutos.setBackground(new java.awt.Color(255, 255, 255));

        gerarRelProduto.setBackground(new java.awt.Color(255, 153, 0));
        gerarRelProduto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        gerarRelProduto.setForeground(new java.awt.Color(255, 255, 255));
        gerarRelProduto.setText("Gerar Relatório");
        gerarRelProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarRelProdutoActionPerformed(evt);
            }
        });

        relProdutoTable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        relProdutoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        relProdutoTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        relProdutoTable.setRowHeight(50);
        relProdutoTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(relProdutoTable);
        if (relProdutoTable.getColumnModel().getColumnCount() > 0) {
            relProdutoTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            relProdutoTable.getColumnModel().getColumn(1).setPreferredWidth(180);
            relProdutoTable.getColumnModel().getColumn(2).setPreferredWidth(40);
            relProdutoTable.getColumnModel().getColumn(3).setPreferredWidth(500);
        }

        javax.swing.GroupLayout relProdutosLayout = new javax.swing.GroupLayout(relProdutos);
        relProdutos.setLayout(relProdutosLayout);
        relProdutosLayout.setHorizontalGroup(
            relProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relProdutosLayout.createSequentialGroup()
                .addGroup(relProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(relProdutosLayout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(gerarRelProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(relProdutosLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        relProdutosLayout.setVerticalGroup(
            relProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relProdutosLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(gerarRelProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jPanel4.add(relProdutos, "relProdutos");

        relVendas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dia (Mínimo)");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mês (Mínimo)");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ano (Mínimo)");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dia (Máximo)");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mês (Máximo)");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Ano (Máximo)");

        diaMintxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        diaMintxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mesMintxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mesMintxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        diaMaxtxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        diaMaxtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        anoMintxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        anoMintxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        anoMaxtxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        anoMaxtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mesMaxtxt.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        mesMaxtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gerarRelVendas.setBackground(new java.awt.Color(255, 153, 0));
        gerarRelVendas.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        gerarRelVendas.setForeground(new java.awt.Color(255, 255, 255));
        gerarRelVendas.setText("Gerar Relatório");
        gerarRelVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarRelVendasActionPerformed(evt);
            }
        });

        relVendasTable.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        relVendasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Pedido", "Valor", "Data", "Hora", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        relVendasTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(relVendasTable);
        if (relVendasTable.getColumnModel().getColumnCount() > 0) {
            relVendasTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            relVendasTable.getColumnModel().getColumn(1).setPreferredWidth(180);
            relVendasTable.getColumnModel().getColumn(2).setPreferredWidth(40);
            relVendasTable.getColumnModel().getColumn(3).setPreferredWidth(40);
        }

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Receita Total");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Pedidos Aceitos");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Pedidos Entregues");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Pedidos Cancelados");

        pedidosEntregues.setBackground(new java.awt.Color(255, 255, 255));
        pedidosEntregues.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        pedidosEntregues.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pedidosEntregues.setToolTipText("");
        pedidosEntregues.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 2, true));
        pedidosEntregues.setPreferredSize(new java.awt.Dimension(50, 24));

        receitaTotal.setBackground(new java.awt.Color(255, 255, 255));
        receitaTotal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        receitaTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        receitaTotal.setToolTipText("A Receita Total é calculada com base nos pedidos que foram entregues e, portanto, devidamente pagos.");
        receitaTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 2, true));
        receitaTotal.setPreferredSize(new java.awt.Dimension(50, 24));
        receitaTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                receitaTotalMouseEntered(evt);
            }
        });

        pedidosAceitos.setBackground(new java.awt.Color(255, 255, 255));
        pedidosAceitos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        pedidosAceitos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pedidosAceitos.setToolTipText("");
        pedidosAceitos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 2, true));
        pedidosAceitos.setPreferredSize(new java.awt.Dimension(50, 24));

        pedidosCancelados.setBackground(new java.awt.Color(255, 255, 255));
        pedidosCancelados.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        pedidosCancelados.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pedidosCancelados.setToolTipText("");
        pedidosCancelados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 2, true));
        pedidosCancelados.setPreferredSize(new java.awt.Dimension(50, 24));

        javax.swing.GroupLayout relVendasLayout = new javax.swing.GroupLayout(relVendas);
        relVendas.setLayout(relVendasLayout);
        relVendasLayout.setHorizontalGroup(
            relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relVendasLayout.createSequentialGroup()
                .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(relVendasLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(diaMintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(mesMintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(anoMintxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(diaMaxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(mesMaxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(anoMaxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(relVendasLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(gerarRelVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(relVendasLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(relVendasLayout.createSequentialGroup()
                                .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(receitaTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(241, 241, 241)
                                .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pedidosAceitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pedidosEntregues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pedidosCancelados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        relVendasLayout.setVerticalGroup(
            relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relVendasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(relVendasLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(diaMintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(relVendasLayout.createSequentialGroup()
                            .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(diaMaxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mesMaxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(relVendasLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(mesMintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(relVendasLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(anoMintxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(relVendasLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anoMaxtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(gerarRelVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(relVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pedidosEntregues, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receitaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pedidosAceitos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pedidosCancelados, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel4.add(relVendas, "relVendas");

        sobre.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 153, 0));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("!");
        jTextField1.setAutoscrolls(false);
        jTextField1.setMinimumSize(new java.awt.Dimension(80, 80));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setText("Bem vindo(a) ao Sistema de Gestão da Lanchonete Best Lanches (v. 2.0)");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane7.setViewportView(jTextArea1);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setText("No momento, você está utilizando o sistema como um colaborador. Todavia, uma vez que se trata de um projeto ainda em construção, você verá que algumas funcionalidades não estão disponíveis através da interface. Caso queira fazer uso dessas funcionalidades, recomendamos que execute o programa através do terminal com a chamada da função startSistema(). ");
        jTextArea2.setWrapStyleWord(true);
        jTextArea2.setAutoscrolls(false);
        jScrollPane8.setViewportView(jTextArea2);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(153, 153, 153));
        jTextArea3.setLineWrap(true);
        jTextArea3.setText("Este programa foi construído pelos alunos Iago Mateus Ávila Fernandes e Mateus Henrique Machado, matriculados na disciplina de \"Programação Orientada a Objetos\" na Universidade Federal dos Vales do Jequitinhonha e Mucuri (UFVJM). ");
        jTextArea3.setWrapStyleWord(true);
        jTextArea3.setAutoscrolls(false);
        jScrollPane9.setViewportView(jTextArea3);

        javax.swing.GroupLayout sobreLayout = new javax.swing.GroupLayout(sobre);
        sobre.setLayout(sobreLayout);
        sobreLayout.setHorizontalGroup(
            sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sobreLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addGroup(sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        sobreLayout.setVerticalGroup(
            sobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sobreLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel4.add(sobre, "sobreColab");

        jMenu1.setText("Sistema");
        jMenu1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Sobre");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pedidos");
        jMenu2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jMenuItem3.setText("Consultar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem7.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jMenuItem7.setText("Extratos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");
        jMenu3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jMenuItem8.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jMenuItem8.setText("Clientes");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jMenuItem9.setText("Colaboradores");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jMenuItem10.setText("Produtos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem12.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jMenuItem12.setText("Estatísticas de venda");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setVisible(false);
        TelaLogin novoLogin = new TelaLogin();
        novoLogin.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CardLayout col1 = (CardLayout) jPanel4.getLayout();
        col1.show(jPanel4, "consPedido");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        CardLayout col1 = (CardLayout) jPanel4.getLayout();
        col1.show(jPanel4, "extPedido");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void cpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfClienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        DateTimeFormatter localDateFormatter = DateTimeFormatter.ofPattern("dd/MM/uuuu");
        DateTimeFormatter localHourFormatter = DateTimeFormatter.ofPattern("HH:mm");
        DefaultTableModel dtmPedidos = (DefaultTableModel) listPedidos.getModel();

        dtmPedidos.setRowCount(0);

        if (ProxyAdministrador.consultaCliente(cpfCliente.getText()) != null) {
            for (Pedido Pe : ProxyAdministrador.consultaCliente(cpfCliente.getText()).getPedidosCliente()) {
                int idPedido = Pe.getIdPedido();

                LocalDate dataPe = LocalDate.parse(Pe.getDataPedido());
                LocalTime horaPe = LocalTime.parse(Pe.getHoraPedido());
                String dataPedido = dataPe.format(localDateFormatter);
                String horaPedido = horaPe.format(localHourFormatter);
                float valorPedido = Pe.getValorTotalPedido();

                Object[] dados = {idPedido, dataPedido, horaPedido, valorPedido};
                dtmPedidos.addRow(dados);
            }

        } else {
            JOptionPane.showMessageDialog(null, "CPF inválido ou não cadastrado. Tente novamente.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void gerarExtratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarExtratosActionPerformed
        DateTimeFormatter localDateFormatter = DateTimeFormatter.ofPattern("dd/MM/uuuu");
        DateTimeFormatter localHourFormatter = DateTimeFormatter.ofPattern("HH:mm");
        DefaultTableModel dtmExtPedidos = (DefaultTableModel) extratosPedidosTabela.getModel();

        dtmExtPedidos.setRowCount(0);

        for (Cliente cl : ProxyAdministrador.getClientes()) {
            for (Pedido pedido : cl.getPedidosCliente()) {
                LocalTime horaPedido = LocalTime.parse(pedido.getHoraPedido());
                LocalDate dataPedido = LocalDate.parse(pedido.getDataPedido());
                Object[] dados = {cl.getCPF(), cl.getNomePessoa() + " " + cl.getSobrenomePessoa(), pedido.getIdPedido(), pedido.getValorTotalPedido(),
                    dataPedido.format(localDateFormatter), horaPedido.format(localHourFormatter)};
                dtmExtPedidos.addRow(dados);
            }
        }


    }//GEN-LAST:event_gerarExtratosActionPerformed

    private void gerarRelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarRelClienteActionPerformed

        DefaultTableModel dtmClientes = (DefaultTableModel) relClienteTable.getModel();
        dtmClientes.setRowCount(0);

        for (Cliente cl : ProxyAdministrador.getClientes()) {
            Object[] dados = {cl.getCPF(), cl.getNomePessoa().toUpperCase() + " " + cl.getSobrenomePessoa().toUpperCase(), cl.getTelefoneCliente(), cl.getEnderecoCliente()};
            dtmClientes.addRow(dados);

        }

        ProxyAdministrador.setQntClientesProtected();
        totalClientes.setText(Integer.toString(ProxyAdministrador.getQntClientesProtected()));

    }//GEN-LAST:event_gerarRelClienteActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        CardLayout col1 = (CardLayout) jPanel4.getLayout();
        col1.show(jPanel4, "relCliente");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        CardLayout col1 = (CardLayout) jPanel4.getLayout();
        col1.show(jPanel4, "relColab");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        CardLayout col1 = (CardLayout) jPanel4.getLayout();
        col1.show(jPanel4, "relProdutos");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        CardLayout col1 = (CardLayout) jPanel4.getLayout();
        col1.show(jPanel4, "relVendas");
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void gerarRelColabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarRelColabActionPerformed
        DefaultTableModel dtmColab = (DefaultTableModel) relColabTable.getModel();
        dtmColab.setRowCount(0);

        for (Colaborador col : ProxyAdministrador.getColaboradores()) {
            if (col != null) {
                Object[] dados = {col.getCPF(), col.getNomePessoa().toUpperCase() + " " + col.getSobrenomePessoa().toUpperCase(), col.getLoginUsuario()};
                dtmColab.addRow(dados);
            }

        }
    }//GEN-LAST:event_gerarRelColabActionPerformed

    private void gerarRelProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarRelProdutoActionPerformed
        DefaultTableModel dtmProd = (DefaultTableModel) relProdutoTable.getModel();
        dtmProd.setRowCount(0);

        for (int i = 0; i < ProxyAdministrador.getListaProdutos().size(); i++) {

            Object[] dados = {ProxyAdministrador.getListaProdutos().get(i).getIdProduto(),
                ProxyAdministrador.getListaProdutos().get(i).getNomeProduto(),
                ProxyAdministrador.getListaProdutos().get(i).getValorProduto(),
                ProxyAdministrador.getListaProdutos().get(i).getDescricaoProduto()};
            dtmProd.addRow(dados);

        }
    }//GEN-LAST:event_gerarRelProdutoActionPerformed

    private void gerarRelVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarRelVendasActionPerformed
        DateTimeFormatter localDateFormatter = DateTimeFormatter.ofPattern("dd/MM/uuuu");
        DateTimeFormatter localHourFormatter = DateTimeFormatter.ofPattern("HH:mm");

        String diaMin = diaMintxt.getText();
        String diaMax = diaMaxtxt.getText();
        String mesMin = mesMintxt.getText();
        String mesMax = mesMaxtxt.getText();
        String anoMin = anoMintxt.getText();
        String anoMax = anoMaxtxt.getText();

        if (diaMin.length() == 1) {
            diaMin = "0" + diaMin;
        }
        if (mesMin.length() == 1) {
            mesMin = "0" + mesMin;
        }
        if (diaMax.length() == 1) {
            diaMax = "0" + diaMax;
        }
        if (mesMax.length() == 1) {
            mesMax = "0" + mesMax;
        }

        String dataMin = anoMin + mesMin + diaMin;
        String dataMax = anoMax + mesMax + diaMax;

        boolean validaMax = ProxyColaborador.isDateValid(dataMin);
        boolean validaMin = ProxyColaborador.isDateValid(dataMax);

        if (validaMax == false || validaMin == false) {
            JOptionPane.showMessageDialog(null, "Intervalo de data inválido. Tente novamente!");
        } else {
            LocalDate dataMinima = LocalDate.parse(anoMin + "-" + mesMin + "-" + diaMin);
            LocalDate dataMaxima = LocalDate.parse(anoMax + "-" + mesMax + "-" + diaMax);
            ArrayList<Cliente> listaClientes = ProxyAdministrador.getClientes();

            float recTotal = 0;
            int qntCancelados = 0;
            int qntAceitos = 0;
            int qntEntregues = 0;
            String statusPedido = "";

            DefaultTableModel dtmVendas = (DefaultTableModel) relVendasTable.getModel();
            dtmVendas.setRowCount(0);

            for (int k = 0; k < listaClientes.size(); k++) {
                for (int j = 0; j < listaClientes.get(k).getPedidosCliente().size(); j++) {
                    LocalDate dataPedido = LocalDate.parse(listaClientes.get(k).getPedidosCliente().get(j).getDataPedido()); //passar o novo formater
                    LocalTime horaPedido = LocalTime.parse(listaClientes.get(k).getPedidosCliente().get(j).getHoraPedido());
                    if (((dataPedido.isEqual(dataMinima)) || (dataPedido.isAfter(dataMinima))) && ((dataPedido.isEqual(dataMaxima)) || (dataPedido.isBefore(dataMaxima)))) {

                        switch (listaClientes.get(k).getPedidosCliente().get(j).getStatusPedido()) {
                            case 1 -> {
                                statusPedido = "ACEITO";
                            }
                            case 2 -> {
                                statusPedido = "EM PREPARO";
                            }
                            case 3 -> {
                                statusPedido = "SAIU PARA ENTREGA";
                            }
                            case 4 -> {
                                qntEntregues++;
                                recTotal += listaClientes.get(k).getPedidosCliente().get(j).getValorTotalPedido();
                                statusPedido = "ENTREGUE";
                            }
                            case 5 -> {
                                qntCancelados++;
                                statusPedido = "CANCELADO";
                            }

                        }

                        qntAceitos++;

                        Object[] dados = {listaClientes.get(k).getCPF(),
                            listaClientes.get(k).getNomePessoa() + " " + listaClientes.get(k).getSobrenomePessoa(),
                            listaClientes.get(k).getPedidosCliente().get(j).getIdPedido(),
                            listaClientes.get(k).getPedidosCliente().get(j).getValorTotalPedido(),
                            dataPedido.format(localDateFormatter), horaPedido.format(localHourFormatter),
                            statusPedido};
                        dtmVendas.addRow(dados);
                    }
                }
            }
            
            receitaTotal.setText(Float.toString(recTotal));
            pedidosAceitos.setText(Integer.toString(qntAceitos));
            pedidosCancelados.setText(Integer.toString(qntCancelados));
            pedidosEntregues.setText(Integer.toString(qntEntregues));

        }


    }//GEN-LAST:event_gerarRelVendasActionPerformed

    private void receitaTotalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receitaTotalMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_receitaTotalMouseEntered

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CardLayout col1 = (CardLayout) jPanel4.getLayout();
        col1.show(jPanel4, "sobreColab");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalColab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalColab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalColab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalColab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalColab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anoMaxtxt;
    private javax.swing.JTextField anoMintxt;
    private javax.swing.JPanel consPedido;
    private javax.swing.JTextField cpfCliente;
    private javax.swing.JTextField diaMaxtxt;
    private javax.swing.JTextField diaMintxt;
    private javax.swing.JPanel extPedido;
    private javax.swing.JTable extratosPedidosTabela;
    private javax.swing.JButton gerarExtratos;
    private javax.swing.JButton gerarRelCliente;
    private javax.swing.JButton gerarRelColab;
    private javax.swing.JButton gerarRelProduto;
    private javax.swing.JButton gerarRelVendas;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable listPedidos;
    private javax.swing.JTextField mesMaxtxt;
    private javax.swing.JTextField mesMintxt;
    private javax.swing.JLabel pedidosAceitos;
    private javax.swing.JLabel pedidosCancelados;
    private javax.swing.JLabel pedidosEntregues;
    private javax.swing.JLabel receitaTotal;
    private javax.swing.JPanel relCliente;
    private javax.swing.JTable relClienteTable;
    private javax.swing.JPanel relColab;
    private javax.swing.JTable relColabTable;
    private javax.swing.JTable relProdutoTable;
    private javax.swing.JPanel relProdutos;
    private javax.swing.JPanel relVendas;
    private javax.swing.JTable relVendasTable;
    private javax.swing.JPanel sobre;
    private javax.swing.JLabel totalClientes;
    // End of variables declaration//GEN-END:variables
}
